### ISSUE TITLE
[QST] How to install from source with system's ucx libs

### ISSUE THREAD

**Issue by cctry** [rapidsai/ucx-py#1047]
Hi,

I am trying to install uxc-py from source using`pip install .` with libucx installed in $CONDA_PREFIX/lib.
I got the error about trying to find the wheel for libucx.
> ERROR: Could not find a version that satisfies the requirement libucx-cu12==1.15.0 (from versions: 1.14.1.post1, 1.15.0.post1, 1.16.0.post1)

How should I avoid this dependency check or direct it to the system's version?

**Comment by pentschev** [comment]
Thanks for your question @cctry , there have been a [few recent changes to our build system](https://github.com/rapidsai/ucx-py/pull/1044) that we also noticed yesterday were breaking changes, we're looking to [have them fixed](https://github.com/rapidsai/ucx-py/pull/1048) by today or early next week. There's also a chance that we'll need to pass more options to `pip install .` which we will document accordingly and update this issue then. If this is an immediate blocker for you, reverting https://github.com/rapidsai/ucx-py/pull/1044 should allow `pip install .` still but that's not going to be a long-term solution.

**Comment by pentschev** [comment]
With https://github.com/rapidsai/ucx-py/pull/1048 now merged, installing via `pip install .` should now be supported again, apologies for the longer than expected delay in hashing out all details.

Since you're using conda, the simpler approach for you is to install the [`ucx` package from conda-forge](https://anaconda.org/conda-forge/ucx), that will most likely cover your needs and you'll still be able to install UCX-Py from source, please refer to the [conda installation docs here](https://ucx-py.readthedocs.io/en/latest/install.html#id2). If you absolutely need the `libucx-cu*` package from PyPI that should be supported as well but it is a much more involved process and much less user-friendly as it requires setting `LD_LIBRARY_PATH` both for install and runtime, refer to [the docs here](https://ucx-py.readthedocs.io/en/latest/install.html#id3). Unfortunately using a custom UCX-Py install with PyPI packages without setting `LD_LIBRARY_PATH` would be a much more challenging and time-consuming effort and thus we do not intend in supporting at the moment.

I'll tentatively close this issue as I believe your case is now resolved, but please feel free to reopen this or open a new issue should you encounter any issues.
