### ISSUE TITLE
Dask-cudf benchmark

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/ucx-py#272]
I’m curious what the status is on getting a dask-cudf dataframe benchmark started.  

My last understanding was that this was blocked by a combination of figuring out the right `UCX_*` environment variables for configuration, and also getting infiniband and NVLINK to work correctly.  Have these been sorted out?  If so, what else do we need to do before we're ready for this?

cc @quasiben @pentschev @randerzander

**Comment by quasiben** [comment]
Agreed.  @jakirkham any interest in pairing up to setup dask-cuda/cudf/numba/ucx and a join test tomorrow ?

**Comment by jakirkham** [comment]
Yeah I think that is a good idea. Have a use case we can work through.

**Comment by quasiben** [comment]
For this benchmark we should be using latest nightly of `dask-cuda` from rapidsai-nightly and something like the following:

```
from dask_cuda import DGX
from dask_cuda.utils import get_ucx_env


ucx_env = get_ucx_env(interface="enp1s0f0", enable_infiniband=False, enable_nvlink=True)
os.environ.update(ucx_env)
dgx = DGX(interface="enp1s0f0", protocol="ucx", enable_tcp_over_ucx=True)
```

@pentschev can you confirm the above is correct ?

**Comment by pentschev** [comment]
Almost, if you want to enable NVLink you must pass `enable_nvlink=True` for both `get_ucx_env` (which will set the correct variables for the client) and to `DGX` (which will set correct variables for scheduler and workers). Similarly `enable_infiniband=True` for InfiniBand, or just `enable_tcp_over_ucx=True` if you only want TCP.

I think what you wanted above is:

```python
from dask_cuda import DGX
from dask_cuda.utils import get_ucx_env


ucx_env = get_ucx_env(interface="enp1s0f0", enable_nvlink=True)
os.environ.update(ucx_env)
dgx = DGX(interface="enp1s0f0", protocol="ucx", enable_nvlink=True)
```

Note that enabling both NVLink or InfiniBand implies enabling TCP, so that can be skipped then.

**Comment by quasiben** [comment]
This has since been handled by https://github.com/rapidsai/dask-cuda/pull/192
