### ISSUE TITLE
Why are we slow with eight GPUs?

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/ucx-py#350]
In https://github.com/rapidsai/ucx-py/wiki/Benchmarks we see that communication speeds are around 10GB/s when using two GPUs, 2GB/s when using four, and 100MB/s when using eight.  Do we have a sense for why this is?

I assume that this has to do with poor routing within a DGX-1.  Perhaps we should try the two-GPU test between poorly connected GPUs and see what is happening there?

**Comment by mrocklin** [comment]
Also, I'm curious if things change when we move to a DGX-2, which has more uniform connectivity.

**Comment by pentschev** [comment]
GPUs on DGX-1 are connected by NVLink in pairs (e.g, GPUs 0 and 1, 2 and 3, etc.), so the communication from one pair to another will go over TCP there unless you use InfiniBand, in which case the communication between pairs will go through that channel. I'm sure DGX-2 will be uniform even without InfiniBand, as all GPUs are interconnected through NVSwitch. On the DGX-2, with 16 GPUs, I'm only not sure whether the first set of 8 GPUs is fully connected to the second set, so there's one place that _maybe_ InfiniBand will still be necessary for best performance.

**Comment by mrocklin** [comment]
Can we use infiniband or some other transport for intra-machine inter-gpu communication?

More generally, are we stuck with 100MB/s transfer speeds on DGX-1's if we use the full machine, or is there something that we can do here.  My guess is that the business folks will want to know if DGX-1s are a reasonable fit for RAPIDS.

**Comment by pentschev** [comment]
Yes, we can. If you enable InfiniBand, the traffic will go through that channel when an NVLink connection isn't available. I have checked that this is the case but I haven't checked if it _always_ takes that path (prefer NVLink, then InfiniBand, and last TCP) or if there's some heuristics to determine where the communication should go through.

**Comment by pentschev** [comment]
I have to correct my previous statement on NVLink connection. It turns out that the [connectivity scheme of DGX-1](https://devblogs.nvidia.com/wp-content/uploads/2017/04/NVLink-topology-e1491278374674.png) is much more complex than that, but it _does not_ provide full connectivity via NVLink on all GPUs, so if there's communication between specific pairs (e.g., GPU 0 to 5, 6 or 7), the communication must choose a different medium (such as PCIe or InfiniBand).

For detailed information, please refer to [NVIDIA DGX-1: The Fastest Deep Learning System](https://devblogs.nvidia.com/dgx-1-fastest-deep-learning-system/).

**Comment by quasiben** [comment]
@mrocklin I ran the cudf benchmark experiment on a dgx 2 and posted the results here:
https://github.com/rapidsai/ucx-py/wiki/Benchmarks-DGX2

**Comment by quasiben** [comment]
I wanted to update this issue with some recent work.  Generally things have improved since we last ran that benchmark. We are now using a pool allocator from RMM and IPC caching is enabled this has greatly improved the NVLINK performance.  Second, recent (though not submitted) work around IB memory registrations have improved performance.  Posted below are  runs on a full DGX (8GPUs) with and without IB.   For this test we see IB gives a ~1.5X performance increase


```
Merge benchmark
-------------------------------
backend        | dask
rows-per-chunk | 100000000
protocol       | ucx
device(s)      | 0,1,2,3,4,5,6,7
rmm-pool       | True
frac-match     | 0.3
tcp            | True
ib             | True
nvlink         | False
data-processed | 25.60 GB
===============================
Wall-clock     | Throughput
-------------------------------
2.00 s         | 12.79 GB/s
2.17 s         | 11.81 GB/s
2.41 s         | 10.60 GB/s
===============================
```

```
Merge benchmark
-------------------------------
backend        | dask
rows-per-chunk | 100000000
protocol       | ucx
device(s)      | 0,1,2,3,4,5,6,7
rmm-pool       | True
frac-match     | 0.3
tcp            | True
ib             | True
nvlink         | True
data-processed | 25.60 GB
===============================
Wall-clock     | Throughput
-------------------------------
1.55 s         | 16.50 GB/s
1.55 s         | 16.55 GB/s
1.33 s         | 19.29 GB/s
===============================
```

**Comment by quasiben** [comment]
For reference here are TCP values:

```
Merge benchmark
-------------------------------
backend        | dask
rows-per-chunk | 100000000
protocol       | tcp
device(s)      | 0,1,2,3,4,5,6,7
rmm-pool       | True
frac-match     | 0.3
data-processed | 25.60 GB
===============================
Wall-clock     | Throughput
-------------------------------
31.85 s        | 803.77 MB/s
35.59 s        | 719.38 MB/s
33.29 s        | 769.06 MB/s
===============================
```

**Comment by mrocklin** [comment]
I'm very happy to see these numbers.  It's great how far this has come over
the last few months.

**Comment by datametrician** [comment]
Should we close this issue now?

**Comment by quasiben** [comment]
I was hoping to close once we have a conda package out which confirms these results

**Comment by quasiben** [comment]
I am going to close this now.  See https://github.com/rapidsai/ucx-py/pull/492#issuecomment-614189237 for recent benchmark numbers.

The answer as to why we are slow with just NVLink and no InfiniBand is because H-to-D / D-to-H is very expensive.  As @pentschev noted, the complex networking architecture of a DGX1 fully connects all the GPUs to one another but *not* over NVLink. However IB devices are interconnected between all device.  We recently discussed this issue and posted benchmarks on a [blog post](https://medium.com/rapids-ai/high-performance-python-communication-with-ucx-py-221ac9623a6a)
