### ISSUE TITLE
Avoiding `__del__` in `TopologicalDistance`

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#365]
Noticed that we are using [`__del__` in the `TopologicalDistance`]( https://github.com/rapidsai/ucx-py/blob/eba981f3e486d4d7305eba5e54b13c11c499e303/ucp/_libs/topological_distance.pyx#L28-L30 ). However this isn't supported for extension types (snippet from the docs below).

> **Note:** There is no `__del__()` method for extension types.

ref: https://cython.readthedocs.io/en/latest/src/userguide/special_methods.html#finalization-method-dealloc

**Comment by jakirkham** [comment]
While `__dealloc__` is a possible option, this relies on Python performing the cleanup. However it is possible interrupt the Python process (as I discovered recently in another use case), in which case the cleanup never occurs.

In other use cases to ensure robust cleanup we have solved this by pushing this into C++ objects that can perform proper RAII and then holding onto these objects in Python object. Perhaps we should consider applying this solution here? Though it would mean we are linking to the C++ stdlib (in case this is a concern, which it probably isn't, but deserves mentioning).

**Comment by pentschev** [comment]
Yeah, I intentionally avoided C++ due to linking, even though it would have been much quicker for me to write the code. I think we can just correct to use `__dealloc__` for now, even though I agree RAII would be safer. I'm not very much concerned about not cleaning hwloc up properly if the Python process gets interrupted, it's very light-weight and I don't think it will cause any major issues in that case, since it only reads information (unlike a driver not cleaning up properly, which could cause a number of issues to keep an engineer having fun debugging for several days). That said, I think adding C++ linkage is not worth the trouble for us at this time.

I will submit a PR to use `__dealloc__` shortly.

**Comment by jakirkham** [comment]
Ok that seems like a good first step at least. Thanks Peter! 😄

It would be good to understand what missing cleanup means in the event it doesn't happen.

**Comment by jakirkham** [comment]
Just one last note (mainly as an FYI/future reference point), `__dealloc__` proceeds through `tp_dealloc`. Relevant snippet from Cython docs below:

> This is done using the `tp_dealloc` slot, which can be customized in Cython by implementing `__dealloc__`.

ref: https://cython.readthedocs.io/en/latest/src/userguide/extension_types.html#controlling-deallocation-and-garbage-collection-in-cpython
