### ISSUE TITLE
Move away from UCX Stream API

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#497]
In `exchange_peer_info` https://github.com/rapidsai/ucx-py/blob/e9a2c92a21551dfece11591dcec0a4ce24ab0a4f/ucp/core.py#L47-L50 :

We use the UCX Stream API for setting up uniquely identifiable matching tags between endpoints. It was recently suggested that we switch to the more mature ucp_tag_send/recv set up endpoints. 

This may be related to errors we first started exploring in https://github.com/rapidsai/ucx-py/issues/495

**Comment by beckernick** [comment]
cc @VibhuJawa @randerzander

**Comment by pentschev** [comment]
After some discussion with @evgeny-leksikov some weeks ago, it became clear that we indeed need the stream API to exchange tags due to the way our communications use cases (e.g., Dask) work. The most common case for UCX is to use a process' rank as the tag, but Dask workers don't have a rank or any similar information that's known _a priori_. Therefore, using the stream API is the recommended way to exchange tags, and that approach is also used by [UCX iodemo](https://github.com/openucx/ucx/blob/d0ae19ead53b99abd37f717018edfcfe13ac14d7/test/apps/iodemo/ucx_wrapper.cc#L884-L913), for example.

We're currently working on support for the UCX Active Message API as well, that can be a full replacement or alternative to the current Stream+Tag matching approach that we use in UCX-Py, as tags aren't really necessary in the Dask use case.

With the above said, I'm going ahead and closing this issue now.
